// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export const metadata = {
  title: "The Wild oasis"
}

import Logo from "./components/Logo";
import Navigation from "./components/navigation";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Logo />
          <Navigation />
        </header>
        <main>{children}</main>
      </body>

    </html>
  )
}
